Add tests for all other ksy files
det-lab/kaitai_struct_awkward_runtime pull request #25
Opened 2024-01-09 20:11 UTC by zonca

- test: improve makefile to compile with patterns
- test: unit test for fake.ksy
- test: generate list of libraries dynamically
- feat: only compile current cpp file
- test: compare the actual array
- test index_option.ksy

2024-01-09 20:15 UTC, zonca commented on tests/test_index_option.py
> +        "0": np.ma.masked_array(data=[], mask=[], dtype=np.uint8).reshape((1, 0)),
@ManasviGoyal I find it suspicious that field "0" has a different shape than field "1" and "2", do you think this is expected in how you generated the data file?

2024-01-10 14:16 UTC, ManasviGoyal commented on tests/test_index_option.py
> +        "0": np.ma.masked_array(data=[], mask=[], dtype=np.uint8).reshape((1, 0)),
The shape is different since the `name` id of `string type`. We have a `ListOffsetBuilder<NumpyBuilder>` in this case instead of just `NumpyBuilder`.

2024-01-15 08:45 UTC, ManasviGoyal requested changes
I tested these with `make test` and it looks good to me.

Can be make the tests run with `pytest` run without running the `make test` first since we need to generate the static library?

2024-01-15 08:45 UTC, ManasviGoyal commented on Makefile
>    JAR_PATH = /usr/share/kaitai-struct-compiler/lib/*
I think for now we should only keep this `JAR_PATH` for now as the other case does not work for `wsl`. To run the tests I had to remove the first condition.

We eventually need to figure out how to make it work for all platforms.

2024-01-15 17:20 UTC, zonca commented on Makefile
>    JAR_PATH = /usr/share/kaitai-struct-compiler/lib/*
ok, removed that line.
Exactly, we need to run `make test` so that all the libraries are built before executing `pytest`

2024-01-15 17:39 UTC, ManasviGoyal approved these changes

2024-01-15 17:40 UTC, merged